

// Login Constants
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_IDLE = 'LOGIN_IDLE';

// SignUp Constants
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_IDLE = 'SIGNUP_IDLE';

// GET_ALL_TOURNAMENTS Constants
export const GET_ALL_TOURNAMENTS_REQUEST = 'GET_ALL_TOURNAMENTS_REQUEST';
export const GET_ALL_TOURNAMENTS_SUCCESS = 'GET_ALL_TOURNAMENTS_SUCCESS';
export const GET_ALL_TOURNAMENTS_FAILURE = 'GET_ALL_TOURNAMENTS_FAILURE';
export const GET_ALL_TOURNAMENTS_IDLE = 'GET_ALL_TOURNAMENTS_IDLE';

// UPCOMING_MATCHES Constants
export const UPCOMING_MATCHES_REQUEST = 'UPCOMING_MATCHES_REQUEST';
export const UPCOMING_MATCHES_SUCCESS = 'UPCOMING_MATCHES_SUCCESS';
export const UPCOMING_MATCHES_FAILURE = 'UPCOMING_MATCHES_FAILURE';
export const UPCOMING_MATCHES_IDLE = 'UPCOMING_MATCHES_IDLE';



